[package]
name = "ulx_reverse"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.4"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "ulx_reverse"
path = "src/main.rs"

[lib]
name = "ulx_reverse"
path = "src/lib.rs"
