[package]
name = "ulx_reverse"
version = "0.1.0"
edition = "2021"

[dependencies]
rusb = "0.9.4"
strum_macros = "0.26.4"

[[bin]]
name = "ulx_reverse"
path = "src/main.rs"

[lib]
name = "ulx_reverse"
path = "src/lib.rs"

[build-dependencies]
winresource = "0.1.17"

[profile.release]
strip = true 
